name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["main"]}
env:
  USER_NAME: 'akshun4'

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: ${{ env.USER_NAME }}
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_introduction: yes
          plugin_followup: yes
          plugin_followup_sections: user, repositories
          plugin_followup_archived: yes
          plugin_habits: yes
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_from: 1000
          plugin_habits_skipped: ${{ env.USER_NAME }}
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_categories: data, markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_details: percentage
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 365
          plugin_languages_recent_load: 1000
          plugin_languages_sections: most-used, recently-used
          plugin_lines: yes
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following
          plugin_reactions: yes
          plugin_reactions_display: absolute
          plugin_reactions_limit: 1000
          plugin_reactions_limit_discussions: 100
          plugin_reactions_limit_discussions_comments: 100
          plugin_reactions_limit_issues: 100
